<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNFgFUE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNFgFUE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNNFgFUE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNNFgFUE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNNFgFUE\App_KernelDevDebugContainer([
    'container.build_hash' => 'NNFgFUE',
    'container.build_id' => '1c6b7216',
    'container.build_time' => 1637922169,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNFgFUE');
